# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1b5003c153b2dc1f8d606552bfd688b1510dd1861b31f21edf3f3de4f7ab9f1ab5ccb97e8fad723a5b67f4988f1a2a57fb43646f9a8117ff49b3896597146da

test:
  secret_key_base: f26ced21b8b74e1da87f71223a86c5f74e2fb792d75ee11804f9f07c1b186f97dc75658cf24006750bd0893a4e6eededd9b7a5c24706fce127bebe2e478a9ecc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
